"""
Week 4 - Part D: Streaming Responses with Google Gemini
Demonstrates real-time token streaming vs waiting for complete block responses.
"""

import os
import sys
import time
from pathlib import Path
from dotenv import load_dotenv

env_path = Path(__file__).resolve().parent / ".env"
load_dotenv(dotenv_path=env_path)

def run_streaming_demo():
    print("=== Streaming Response Demo (Google Gemini) ===")
    
    gemini_key = os.getenv("GEMINI_API_KEY")

    if gemini_key and not gemini_key.startswith("your_"):
        try:
            import google.generativeai as genai
            genai.configure(api_key=gemini_key)
            model = genai.GenerativeModel("gemini-1.5-flash")

            prompt = "Explain why token streaming provides a better user experience in two concise sentences."
            print(f"Prompt: {prompt}\nStreaming: ", end="", flush=True)

            response = model.generate_content(prompt, stream=True)
            for chunk in response:
                print(chunk.text, end="", flush=True)
            print("\n\n[Streaming complete]")
            return
        except Exception as ex:
            print(f"\n[!] Live API Note: {ex}. Running simulated streaming demonstration.\n")

    # Offline / Educational simulation
    sample_text = "Token streaming allows applications to render text chunks immediately as they are generated by Google Gemini, dramatically reducing perceived latency for interactive reading interfaces."
    print("AI Response: ", end="", flush=True)
    for word in sample_text.split(" "):
        print(word + " ", end="", flush=True)
        time.sleep(0.05)
    print("\n\n[Streaming complete]")

if __name__ == "__main__":
    run_streaming_demo()
